first-names = [
    "Jhon",
    "Sven",
    "Jane"
]
last-names = [
    "Doe",
    "Specimin",
]

[[aliases]]
ip = "127.0.0.1"
name = "Localhost"

[[aliases]]
ip = "127.0.0.2"
name = "Prod"

[[quick-users]]
label = "test"
ssn = "201604064188"
name = "Test Testsson"